# Create User
POST http://localhost:3000/users
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "wahtever2@this.net",
  "password": "test123!!"
}
###

# Create Many User
POST http://localhost:3000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZWEzOTMyMi1hYjlhLTQ4MGYtOTBjYi0xMzFhMDM4MDk0OWYiLCJlbWFpbCI6IndhaHRldmVyMkB0aGlzLm5ldCIsImlhdCI6MTc0OTM5NTQwMSwiZXhwIjoxNzQ5Mzk5MDAxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.aHJezngYYxgm8C-YJMb6OYuslSin8kNbaLtx6ocbA9Q

{
  "users": [
    {
      "firstName": "Bill",
      "lastName": "Boop",
      "email": "bill@boop.net",
      "password": "test123!!"
    },
    {
      "firstName": "Jim",
      "lastName": "Dorf",
      "email": "jim@dorf.net",
      "password": "test123!!"
    },
    {
      "firstName": "Jacques",
      "lastName": "Doe",
      "email": "wahtever@that.net",
      "password": "test123!!"
    }
  ]
}
###
