POST http://localhost:3000/posts
Content-Type: application/json

{
  "title": "Something Else",
  "postType": "post",
  "slug": "something-else",
  "status": "draft",
  "content": "post-content",
  "schema": "{\r\n    \"@context\": \"https:\/\/schema.org\",\r\n    \"@type\": \"Person\"\r\n  }",
  "featuredImageUrl": "http://localhost.com/images/image1.jpg",
  "publishOn": "2024-03-16T07:46:32+0000",
  "tags": [
    "626121fd-35c5-4642-9219-aaf933af1b7c"

  ],
  "authorId": "715600a5-af74-4eb9-9287-8dc68adddb49"
}

###
